language: python

python:
  - "2.7"
  - "3.5"

sudo: required

services:
  - docker

# to build container
# install:
#  - docker-compose build web

# command to run tests
script:
  - docker-compose build web
  - docker-compose run web py.test
  - docker-compose run web py.test --cov=. --cov-report=xml
