sudo: required
services:
  - docker
script:
  - ln -s ./docker/docker-compose.yml ./docker-compose.yml
  - docker-compose build
  # test if we are able to setup database schema properly
  # should catch most typical errors in migrations
  - docker-compose run --rm web python manage.py migrate
  - docker-compose run --rm web py.test --cov=.
