language: python

python:
  - "2.7"
  - "3.5"

sudo: required

services:
  - docker

install:
- docker-compose build web


# command to install dependencies
# install: "pip install -r requirements.txt"
# command to run tests
# script: pytest