language: python

python:
  - "2.7"
  - "3.5"

sudo: required

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.6.2


# command to install dependencies
# install: "pip install -r requirements.txt"
# command to run tests
# script: pytest