version: '2.1'

services:

  db:
    build:
      context: ./docker/db/
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
    healthcheck:
      test: "exit 0"

  web:
    build:
      context: ./docker/web/
      dockerfile: Dockerfile
    user: root
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/code/
    ports:
      - "8080:8080"
    environment:
      DJANGO_SETTINGS_MODULE: EnviroMonitorWeb.settings.dev
    command: python manage.py runserver 0.0.0.0:8080
    restart: unless-stopped

  test:
    build:
      context: ./docker/web/
      dockerfile: Dockerfile
    user: root
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/code/
    environment:
      DJANGO_SETTINGS_MODULE: EnviroMonitorWeb.settings.test
    command: py.test -s --cov=.
