# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 11:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Metering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pm01', models.FloatField()),
                ('pm25', models.FloatField()),
                ('pm10', models.FloatField()),
                ('temp_out1', models.FloatField()),
                ('temp_out2', models.FloatField(max_length=100)),
                ('temp_out3', models.FloatField()),
                ('hum_out1', models.FloatField()),
                ('hum_out2', models.FloatField()),
                ('hum_out3', models.FloatField()),
                ('temp_int1', models.FloatField()),
                ('hum_int1', models.TextField(max_length=100)),
                ('rssi', models.FloatField()),
                ('bpress_out1', models.FloatField()),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('project_website', models.URLField()),
                ('description', models.TextField(max_length=4000)),
                ('logo', models.FilePathField(blank=True)),
                ('project_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('type', models.TextField(max_length=100)),
                ('notes', models.TextField(max_length=100)),
                ('test', models.BooleanField()),
                ('position', models.TextField(max_length=100)),
                ('country', models.TextField(max_length=30)),
                ('state', models.TextField(max_length=100)),
                ('county', models.TextField(max_length=100)),
                ('community', models.TextField(max_length=100)),
                ('city', models.TextField(max_length=100)),
                ('district', models.TextField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='metering',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Station'),
        ),
    ]
