# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 08:45
from __future__ import unicode_literals

import api.utils
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_admin',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='last_updated',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_website',
            new_name='website',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='last_updated',
            new_name='updated',
        ),
        migrations.RemoveField(
            model_name='metering',
            name='id',
        ),
        migrations.RemoveField(
            model_name='station',
            name='test',
        ),
        migrations.AddField(
            model_name='metering',
            name='is_test',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether entry was created using Sensor test mode (Sensor.is_in_test_mode=True).'),
        ),
        migrations.AddField(
            model_name='station',
            name='altitude',
            field=models.FloatField(default=0, help_text='Altitude of sensor location.'),
        ),
        migrations.AddField(
            model_name='station',
            name='is_in_test_mode',
            field=models.BooleanField(default=False, help_text='Whether sensor is in test mode or not (all data).'),
        ),
        migrations.AddField(
            model_name='station',
            name='token',
            field=models.CharField(default=api.utils.generate_token, help_text='Token automatically generated while saving model, needed by Station to POST any data.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='metering',
            name='bpress_out1',
            field=models.FloatField(help_text='Outside absolute barometric pressure sensor1, in hPa.'),
        ),
        migrations.AlterField(
            model_name='metering',
            name='created',
            field=models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='metering',
            name='hum_int1',
            field=models.FloatField(help_text='Internal relative humidity sensor1 (air sucked by PM sensor), in %.'),
        ),
        migrations.AlterField(
            model_name='metering',
            name='hum_out1',
            field=models.FloatField(help_text='Outside relative humidity sensor1, in %.'),
        ),
        migrations.AlterField(
            model_name='metering',
            name='hum_out2',
            field=models.FloatField(blank=True, default=None, help_text='Outside relative humidity sensor2, optional, in %.', null=True),
        ),
        migrations.AlterField(
            model_name='metering',
            name='hum_out3',
            field=models.FloatField(blank=True, default=None, help_text='Outside relative humidity sensor3, optional, in %.', null=True),
        ),
        migrations.AlterField(
            model_name='metering',
            name='pm01',
            field=models.FloatField(help_text='PM 0.1 in ug/m^3'),
        ),
        migrations.AlterField(
            model_name='metering',
            name='pm10',
            field=models.FloatField(help_text='PM 10 in ug/m^3'),
        ),
        migrations.AlterField(
            model_name='metering',
            name='pm25',
            field=models.FloatField(help_text='PM 2.5 in ug/m^3'),
        ),
        migrations.AlterField(
            model_name='metering',
            name='rssi',
            field=models.FloatField(help_text='RSSI of WiFi (signal strength). For debugging "vanishing" stations.'),
        ),
        migrations.AlterField(
            model_name='metering',
            name='temp_int1',
            field=models.FloatField(help_text='Internal temperature sensor1 (air sucked by PM sensor), in C.'),
        ),
        migrations.AlterField(
            model_name='metering',
            name='temp_out1',
            field=models.FloatField(help_text='Outside temperature sensor1, in C.'),
        ),
        migrations.AlterField(
            model_name='metering',
            name='temp_out2',
            field=models.FloatField(blank=True, default=None, help_text='Outside temperature sensor2, optional, in C.', null=True),
        ),
        migrations.AlterField(
            model_name='metering',
            name='temp_out3',
            field=models.FloatField(blank=True, default=None, help_text='Outside temperature sensor3, optional, in C.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='station',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='station',
            name='community',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='station',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='station',
            name='county',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='station',
            name='district',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='station',
            name='notes',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='station',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(help_text='Exact sensor position on map.', srid=4326),
        ),
        migrations.AlterField(
            model_name='station',
            name='state',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='station',
            name='type',
            field=models.CharField(choices=[('1', 'EM0.1'), ('2', 'EM1'), ('3', 'CUSTOM')], max_length=1),
        ),
    ]
