# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_meteringhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metering',
            old_name='hum_int1',
            new_name='hum_int_air1',
        ),
        migrations.RenameField(
            model_name='metering',
            old_name='temp_int1',
            new_name='temp_int_air1',
        ),
        migrations.RenameField(
            model_name='meteringhistory',
            old_name='hum_int1',
            new_name='hum_int_air1',
        ),
        migrations.RenameField(
            model_name='meteringhistory',
            old_name='temp_int1',
            new_name='temp_int_air1',
        ),
    ]
