# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 12:39
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170113_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='city',
            field=models.CharField(default='', help_text='administration level 4', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='community',
            field=models.CharField(default='', help_text='administration level 3', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='country',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='county',
            field=models.CharField(default='', help_text='administration level 2', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='district',
            field=models.CharField(default='', help_text='administration level 5', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(default=None, help_text='Exact position on map.', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.CharField(default='', help_text='administration level 1', max_length=255),
        ),
        migrations.AlterField(
            model_name='station',
            name='city',
            field=models.CharField(default='', help_text='administration level 4', max_length=255),
        ),
        migrations.AlterField(
            model_name='station',
            name='community',
            field=models.CharField(default='', help_text='administration level 3', max_length=255),
        ),
        migrations.AlterField(
            model_name='station',
            name='country',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='station',
            name='county',
            field=models.CharField(default='', help_text='administration level 2', max_length=255),
        ),
        migrations.AlterField(
            model_name='station',
            name='district',
            field=models.CharField(default='', help_text='administration level 5', max_length=255),
        ),
        migrations.AlterField(
            model_name='station',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(default=None, help_text='Exact position on map.', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='station',
            name='state',
            field=models.CharField(default='', help_text='administration level 1', max_length=255),
        ),
    ]
