# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170120_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, upload_to='project/'),
        ),
    ]
