# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-22 11:01
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170206_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True),
        ),
    ]
