# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-24 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170222_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='metering',
            name='hw_id',
            field=models.CharField(default='', help_text='Unique ID of station hardware that created Metering.', max_length=255),
        ),
        migrations.AddField(
            model_name='meteringhistory',
            name='hw_id',
            field=models.CharField(default='', help_text='Unique ID of station hardware that created Metering.', max_length=255),
        ),
    ]
