# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170324_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metering',
            name='bpress_out1',
            field=models.FloatField(blank=True, default=None, help_text='Outside absolute barometric pressure sensor1, in hPa.', null=True),
        ),
        migrations.AlterField(
            model_name='metering',
            name='hum_int_air1',
            field=models.FloatField(blank=True, default=None, help_text='Internal relative humidity sensor1 (air sucked by PM sensor), in %.', null=True),
        ),
        migrations.AlterField(
            model_name='metering',
            name='hum_out1',
            field=models.FloatField(blank=True, default=None, help_text='Outside relative humidity sensor1, in %.', null=True),
        ),
        migrations.AlterField(
            model_name='metering',
            name='rssi',
            field=models.FloatField(blank=True, default=None, help_text='RSSI of WiFi (signal strength). For debugging "vanishing" stations.', null=True),
        ),
        migrations.AlterField(
            model_name='metering',
            name='temp_int_air1',
            field=models.FloatField(blank=True, default=None, help_text='Internal temperature sensor1 (air sucked by PM sensor), in C.', null=True),
        ),
        migrations.AlterField(
            model_name='meteringhistory',
            name='bpress_out1',
            field=models.FloatField(blank=True, default=None, help_text='Outside absolute barometric pressure sensor1, in hPa.', null=True),
        ),
        migrations.AlterField(
            model_name='meteringhistory',
            name='hum_int_air1',
            field=models.FloatField(blank=True, default=None, help_text='Internal relative humidity sensor1 (air sucked by PM sensor), in %.', null=True),
        ),
        migrations.AlterField(
            model_name='meteringhistory',
            name='hum_out1',
            field=models.FloatField(blank=True, default=None, help_text='Outside relative humidity sensor1, in %.', null=True),
        ),
        migrations.AlterField(
            model_name='meteringhistory',
            name='rssi',
            field=models.FloatField(blank=True, default=None, help_text='RSSI of WiFi (signal strength). For debugging "vanishing" stations.', null=True),
        ),
        migrations.AlterField(
            model_name='meteringhistory',
            name='temp_int_air1',
            field=models.FloatField(blank=True, default=None, help_text='Internal temperature sensor1 (air sucked by PM sensor), in C.', null=True),
        ),
    ]
