# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20170407_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='type',
            field=models.CharField(choices=[('smogly', 'SMOGLY'), ('custom', 'CUSTOM'), ('aqicn', 'AQICN'), ('basic-sds011', 'BASIC-SDS011')], default='smogly', max_length=30),
        ),
    ]
